service.name: PetPar
swagger:
  title: API para o web site de adoção de animais Petpar
  description: Essa API tem como objetivo disponibilizar todo a funcionalidade do site envolvendo usuarios, instituições, animais e doações
  version: 1.0.0
request-queue:
  period: "0 0 * * 0"
  requests-amount: 10
  scheduler-enabled: true
  month-period: 2
spring:
  application:
      name:
  jpa:
    database: MYSQL
  datasource:
    url: "jdbc:mysql://localhost:3307/PetPar?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC"
    password: "root"
    username: "root"